# only example
pinpoint-agent:
  image: pinpoint-agent:1.6.0
  #net: "none"
  restart: unless-stopped
  volumes:
    - /opt/pinpoint:/opt/pinpoint-1.6.0/app
  ports:
    - 9111:9111
  environment:
    PINPOINT_APP_HOME: /opt/pinpoint-1.6.0/app
    APP_NAME: ExampleApp
    APP_PATH: /opt/pinpoint-1.6.0/app/example.jar
    COLLECTOR_IP: 192.168.1.11
    #COLLECTOR_TCP_PORT: 9994
    #COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
    #COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
    DISABLE_DEBUG: 'true'
