pinpoint-mysql:
  container_name: pinpoint-mysql
  restart: always
  image: mysql:5.7
  ports:
    - "13306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root123
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_DATABASE=pinpoint

pinpoint-collector:
  container_name: pinpoint-collector
  hostname: collector
  image: pinpoint-collector:1.6.0
  restart: always
  expose:
    - "9994"
    - "9995"
    - "9996"
  ports:
    - "9994:9994"
    - "9995:9995/tcp"
    - "9996:9996/tcp"
    - "9995:9995/udp"
    - "9996:9996/udp"
  environment:
    HBASE_HOST: 192.168.1.188
    HBASE_PORT: 2181
    COLLECTOR_TCP_PORT: 9994
    COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
    COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
    CLUSTER_ENABLE: 'true'
    CLUSTER_ZOOKEEPER_ADDRESS: 192.168.1.188
    DISABLE_DEBUG: 'true'
 
pinpoint-web:
  container_name: pinpoint-web
  hostname: web
  image: pinpoint-web:1.6.0
  restart: always
  expose:
    - "8080"
  ports:
    - "3080:8080"
  environment:
    HBASE_HOST: 192.168.1.188
    HBASE_PORT: 2181
    CLUSTER_ENABLE: 'true'
    CLUSTER_ZOOKEEPER_ADDRESS: 192.168.1.188
    ADMIN_PASSWORD: admin123
    DISABLE_DEBUG: 'true'
    JDBC_DRIVER: com.mysql.jdbc.Driver
    JDBC_URL: jdbc:mysql://mysql:3306/pinpoint?characterEncoding=UTF-8
    JDBC_USERNAME: admin
    JDBC_PASSWORD: admin
  links:
    - pinpoint-mysql:mysql

# only example
#pinpoint-agent:
#  image: naver/pinpoint-agent:1.6.0
#  net: "none"
#  restart: unless-stopped
#  volumes:
#    - /var/container_data/pinpoint-agent/log:/opt/app/pinpoint-agent/log:rw
#  environment:
#    COLLECTOR_IP: 192.168.99.100
#    COLLECTOR_TCP_PORT: 9994
#    COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
#    COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
#    DISABLE_DEBUG: 'true'
